name: Bug report
description: Report a reproducible problem to help us improve
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please fill out all required fields.
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `mesh --version` or crate versions
      placeholder: 0.1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce, ideally with logs
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true
